### ISSUE TITLE
ruby gem for dalle 2 API

### ISSUE THREAD

**Issue by 3rwolff** [alexrudall/ruby-openai#114]
Hello, I love your gem, I used it to install some crazy cool text based features in out app.

OpenAI has a dalle 2 API coming out at some point soon. Do you plan to make a ruby gem that could interface with that? I would love to see another great gem from your guys using that new resource.

**Comment by alexrudall** [comment]
Hi @3rwolff 

Thanks a lot for the kind words! What's your app? Can I add a link to it to the README?

Yes, I will definitely look at building out a gem for that, either separately or as part of this one. If it comes out and I miss it please drop me a comment here to remind me :)

**Comment by chadwilken** [comment]
The API is now live https://openai.com/blog/dall-e-api-now-available-in-public-beta/ :).

**Comment by 3rwolff** [comment]
Hello @alexrudall I work as a software engineer on a Rails web app called Live Oak Computer Science (https://liveoakcs.com/). Our app aims to provide curriculum to teachers who may not be trained in CS but due to recent legislations have to begin teaching middle and high school students CS.

**Comment by alexrudall** [comment]
Thanks @3rwolff really appreciate that! The [latest version](https://rubygems.org/gems/ruby-openai/versions/2.1.0) of ruby-openai adds `Images#generate` 🤖 ❤️ 🦦

**Comment by 3rwolff** [comment]
Awesome work @alexrudall, thank you very much for implementing that change!
