### ISSUE TITLE
Dalle Support

### ISSUE THREAD

**Issue by kieranklaassen** [alexrudall/ruby-openai#117]
Any plans to add https://beta.openai.com/docs/guides/images/introduction ?

**Comment by makevoid** [comment]
let me start to say that I used `ruby-openai` for gpt3 and it works great

----

As it's not (yet) supporting Dalle, In the meantime I am using this gist:

https://gist.github.com/makevoid/1d1529a15f51aa27be70f20874b37054

samples: https://twitter.com/makevoid/status/1588802240000950273

hope this is helpful :)

**Comment by alexrudall** [comment]
Thanks both, [2.1.0](https://github.com/alexrudall/ruby-openai/pull/119/files) adds `Image#generate` as a first step on this!
