### ISSUE TITLE
Allow clients to have different OpenAI configurations

### ISSUE THREAD

**Issue by petergoldstein** [alexrudall/ruby-openai#149]
**Is your feature request related to a problem? Please describe.**

I want to build a platform such that I can use multiple OpenAI credentials and configurations.  For example, I may have a SaaS that uses models from different organizations.  Or I may want to tier my users, such that one tier of users gets access to OpenAI at a higher usage threshold.  In these cases I want a single application to be able to define a Client object with a given configuration for a per-user context.  Currently that's not possible with this library.

**Describe the solution you'd like**

I thought that the global configuration would be a default, that could be overridden on creation of a `OpenAI::Client` object.  Instead, based on the code [here](https://github.com/alexrudall/ruby-openai/blob/0519baa062cb97037ffb8fa6c7bae8ac42f59ee6/lib/ruby/openai/client.rb#L5), invocation of a client overwrites the global configuration.  

Converting the code to a global default, overriddable on a per-client basis, would be fairly straightforward for everything except the `organization_id` (since you might have a non-null default, which could be overridden on a per-client basis, potentially with nil).

Leaving this problem aside, this change could be accomplished with the following steps:

1. The initializer for `OpenAI::Client` would be rewritten to set per-instance values for `access_token`, `organization_id`, and `api_version` based on arguments and default to those stored in `Ruby::OpenAI::configuration` if nil (or a NullObject for `organization_id`)
2. There'd be a general conversion of the `OpenAI::Client` class methods to instance methods, potentially leaving the existing public class methods in place as ones that use the 'default' client (one that uses the global configuration)

I recognize that this would be a pretty significant change, but as-is the gem can't support any real multi-tenant use case. My thoughts would be that this might make sense as a v4 change.

**Describe alternatives you've considered**

None really.  This is how most libraries of this nature (including [Dalli](https://github.com/petergoldstein/dalli), which I maintain) handle multi-tenancy with default configurations. The organization_id makes it somewhat more ambiguous, but could probably be solved pretty easily with a NullObject pattern in the `OpenAI::Client` initializer.

**Additional context**

I'd be happy to put up a PR if there's interest. 

It might also make sense to look at supporting connection pools as a further step towards supporting usage in a multi-tenant SaaS.

**Comment by alexrudall** [comment]
This sounds cool and smart change. Agree it would probably be breaking and require a major version bump but hopefully not too onerous a change for upgrading users. A key goal for me with this library is making it as simple and easy to get started with as possible for beginners, but as long as this doesn't interfere with that definitely welcome more power features like this. 

Would welcome a quick and dirty PR to review the approach and help me think it through in practice. Really appreciate your contributions and suggestions! Dalli looks like a sick project btw, not come across it before

**Comment by unixneo** [comment]
Please do not make breaking changes.

Fork and create a new repo if you plan breaking changes.

Thanks

**Comment by bf4** [comment]
PR in https://github.com/alexrudall/ruby-openai/pull/150 looks good. I'd like to 👍 getting it rebased and merged.

**Comment by MarioRuiz** [comment]
please what's the current situation on this?

**Comment by alexrudall** [comment]
Happy to get this one rebased and tested and merged as it seems there's quite a bit of demand. Can I ask how this is affecting you / causing problems @MarioRuiz ? That will help me test the feature. Thanks!

**Comment by MarioRuiz** [comment]
We will give support on our SmartBot https://github.com/MarioRuiz/slack-smart-bot#openai to be able to use different hosts, access tokens or api types by user. So for example it could be a default host and access token for all users but everyone could supply specific ones for certain services. So for example an use case would be:
* All users inside ACME company will use by default chatGPT Azure host and the company access token. No Whisper and no DallE
* Peter wants to use his personal access token from openai host to access whisper and DallE
* Anna wants to try chatGPT with her personal access token against openai host since she has access to GPT4 and ACME doesn't

**Comment by alexrudall** [comment]
Thanks @MarioRuiz ! Continuing this in #260

**Comment by alexrudall** [comment]
This PR #260 is ready, would appreciate any review, test, feedback that anyone can offer. @petergoldstein particularly I would be very grateful if you have time to give it a once over. Thanks again for your work on this a few months ago.

**Comment by alexrudall** [comment]
Released in [v5](https://rubygems.org/gems/ruby-openai/versions/5.0.0). Thanks again for the work different people did on this!
