### ISSUE TITLE
Feature Request:  Method to Detect GPT-3 Generated Text

### ISSUE THREAD

**Issue by unixneo** [alexrudall/ruby-openai#159]
As, as a part of this useful code, it would be good to add one or methods which can be used to detect OpenAI generated code.

Please consider this for the future.

**Comment by alexrudall** [comment]
This is a hard problem! The only way I could imagine OpenAI doing this with 100% reliability would be to save ALL the text generated by their APIs and then perform searches against it, but this seems inefficient. If OpenAI do add this feature or similar I'll be sure to add it to this library :)
