### ISSUE TITLE
Show "usage" for Image Generation/Variations

### ISSUE THREAD

**Issue by ustincameron** [alexrudall/ruby-openai#161]
The text completion models contain a "usage" object that allows us to see how much the generation costs, but it seems the image generation is lacking the same object.

```
	"usage": {
		"prompt_tokens": 54,
		"completion_tokens": 23,
		"total_tokens": 77
	}
```

Any documentation around this credit cost or thoughts on adding this?

**Comment by alexrudall** [comment]
Hi @ustincameron, thanks for this, I've raised it over at the [OpenAI forum](https://community.openai.com/t/feature-request-token-usage-in-dalle-api-responses/34134) so let's see what they come back with. The DALLE API is still in beta so I expect they will add it at some point.
