### ISSUE TITLE
Allow OpenAI::Client to receive an options hash on initialization and pass it to the HTTParty client

### ISSUE THREAD

**Issue by khalilgharbaoui** [alexrudall/ruby-openai#164]
Getting:
`Net::ReadTimeout - Net::ReadTimeout with #<TCPSocket:(closed)>:`

Need to be able to pass an `options` hash the `OpenAI::Client.new` (which will end up in HTTParty options) for more granular control over the request handling.

Example:
```
# use a read_timeout of 100ms
HTTParty.get('http://www.example.com', { read_timeout: 0.1 })
```

**Comment by richardonrails** [comment]
+1, I'm getting `Net::ReadTimeout` errors and would like to extend the timeout.

**Comment by kiosan** [comment]
+1

**Comment by richardonrails** [comment]
@alexrudall Would you accept a Pull Request that implements this?

**Comment by alexrudall** [comment]
Hi @richardonrails, thanks for the offer, I would!

**Comment by alexrudall** [comment]
Actually, @richardonrails, I think we're going to move away from HTTParty and probably switch to [Typhoeus](https://github.com/typhoeus/typhoeus) soon which has no timeout by default I think, so probably hang fire for now

**Comment by frmsaul** [comment]
+1

**Comment by waqasdevgit** [comment]
+1

**Comment by frmsaul** [comment]
Thanks!
