### ISSUE TITLE
Deleting models

### ISSUE THREAD

**Issue by lancecarlson** [alexrudall/ruby-openai#168]
**Describe the bug**
I noticed that the API supports deleting models, but this client does not. Oddly enough I tried to add deleting models into this client and tried to delete my model and it didn't work. Did you experience the same issue and that's why it's not supported? Also awkward that it's documented under the finetunes endpoint but its path looks more like it's under the Models CRUD.

https://beta.openai.com/docs/api-reference/fine-tunes/delete-model

**Comment by alexrudall** [comment]
Thanks @lancecarlson, [3.1.0](https://rubygems.org/gems/ruby-openai/versions/3.1.0) adds `Finetunes#delete` to cover this
