### ISSUE TITLE
Getting  expected multipart/form-data when uploading jsonl fine tuning and training data

### ISSUE THREAD

**Issue by tymat** [alexrudall/ruby-openai#170]
**Describe the bug**
Trying to upload fine tune data as described in the `README.md` but my dataset is about 42mb in size.  

```
client = OpenAI::Client.new(access_token: "XXX")
response = client.files.upload(parameters: { file: "chases_training.jsonl", purpose: "fine-tune" })
```

This produces the following errors:

```
{"error"=>
  {"message"=>
    "Invalid Content-Type header (application/json), expected multipart/form-data. (HINT: If you're using curl, you can pass -H 'Content-Type: multipart/form-data')",
   "type"=>"invalid_request_error",
   "param"=>nil,
   "code"=>nil}}
```

**To Reproduce**
1. Follow the same steps as the README file of this project
2. Try using a larger file

**Expected behavior**
It should upload the file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Ventura 13.1

**Additional context**
I prepared the training data using [these instructions](https://beta.openai.com/docs/guides/fine-tuning)

**Comment by alexrudall** [comment]
Hi @tymat, thanks for reporting this. Would it be possible to share an example file to help me reproduce this easily?

**Comment by MrHubble** [comment]
@tymat were you able to resolve this?
