### ISSUE TITLE
Tokenizer

### ISSUE THREAD

**Issue by richardonrails** [alexrudall/ruby-openai#176]
https://beta.openai.com/tokenizer says:

> If you need a programmatic interface for tokenizing text, check out the [transformers](https://huggingface.co/docs/transformers/model_doc/gpt2#transformers.GPT2TokenizerFast) package for python or the [gpt-3-encoder](https://www.npmjs.com/package/gpt-3-encoder) package for node.js.

It'd be nice to have a similar method in this package for Ruby

**Comment by richardonrails** [comment]
Specifically: To know how many tokens a given prompt is.

**Comment by kojix2** [comment]
Sorry, I was just looking for a Ruby library that I think ChatGPT can use and I accidentally came across this page. By any chance, are you looking for this?

https://github.com/ankane/tokenizers-ruby

```ruby
s = "In a hole in the ground there lived a hobbit."
tokenizer = Tokenizers.from_pretrained("gpt2")
ids = tokenizer.encode(s).ids
tokenizer.decode(ids)
```

https://github.com/ankane/blingfire-ruby

```
s = "In a hole in the ground there lived a hobbit."
encoder = BlingFire.load_model('gpt2.bin')
decoder = BlingFire.load_model('gpt2.i2w')
ids = encoder.text_to_ids(s)
decoder.ids_to_text(ids)
```

**Comment by richardonrails** [comment]
@kojix2 Thanks. I admit I didn't search for other libraries before requesting here, since I was already using this library for OpenAI GPT-3 integration. Do you know if GPT2 and GPT3 tokenization is the same? I basically just want to get the longest possible response from the Completions API but instead of passing `max_tokens: 4096` (for `text-davinci-00`) it appears I need to do `max_token: 4096 - tokens_from_prompt(my_dynamic_prompt)`.

**Comment by kojix2** [comment]
There is a Stack Exchange page that states they are the same. In fact, when I tried a simple example, it matched. However, I am not sure if they are the same in all cases.

https://datascience.stackexchange.com/questions/97630/what-tokenizer-does-openais-gpt3-api-use

**Comment by richardonrails** [comment]
Thank you! I'm going with this:

https://github.com/ankane/tokenizers-ruby
```rb
tokenizer = Tokenizers.from_pretrained('gpt2')
encoded = tokenizer.encode(prompt, add_special_tokens: true)
prompt_tokens = encoded.tokens.length
```

**Comment by arjun810** [comment]
Some folks made js and java bindings for tiktoken, and we built a little ruby wrapper based off their work:
https://github.com/volition-co/tiktoken

It can be installed with `gem install tiktoken`

Still need to document it, but briefly:

```
enc = Tiktoken::encoding_for_model('gpt2')
enc2 = Tiktoken::get_encoding('p50k_base')
tokens = enc.encode(prompt)
prompt = enc.decode(tokens)
```
