### ISSUE TITLE
Please Add : Retrieve file content

### ISSUE THREAD

**Issue by unixneo** [alexrudall/ruby-openai#178]
**Is your feature request related to a problem? Please describe.**

Yes, we need to retrieve fine-tune file contents.  This API endpoint is missing from this gem.

**Describe the solution you'd like**

Per the API:

[Retrieve file content](https://beta.openai.com/docs/api-reference/files/retrieve-content)

```
GET
 
https://api.openai.com/v1/files/{file_id}/content

Returns the contents of the specified file

```

Thanks.

**Comment by alexrudall** [comment]
Thanks @unixneo, added in [3.2.0](https://rubygems.org/gems/ruby-openai/versions/3.2.0)
