### ISSUE TITLE
NoMethodError: undefined method `arity' for "application/json":String

### ISSUE THREAD

**Issue by sajjadmurtaza** [alexrudall/ruby-openai#182]
**Describe the bug**
NoMethodError: undefined method `arity' for "application/json":String

**To Reproduce**
1. client = OpenAI::Client.new(access_token: '<TOKEN>')
2. client.models.list

**Expected behavior**
No Error

**Screenshots**
<img width="1128" alt="Screenshot 2023-02-10 at 13 58 37" src="https://user-images.githubusercontent.com/8552702/218098200-cecf8aaa-2cb2-48dc-95de-ba105155ab86.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by alexrudall** [comment]
Hi @sajjadmurtaza, I'm not able to reproduce this. Can you share what version of `ruby-openai` you are using?
