### ISSUE TITLE
Add Chat and Whisper functionality

### ISSUE THREAD

**Issue by benhalpern** [alexrudall/ruby-openai#198]
**Is your feature request related to a problem? Please describe.**
OpenAI added new functionality:

https://platform.openai.com/docs/guides/chat
https://platform.openai.com/docs/guides/speech-to-text

**Describe the solution you'd like**
Let's get this library up-to-date :)

**Comment by alexrudall** [comment]
Chat is released in version [v.4](https://rubygems.org/gems/ruby-openai/versions/3.4.0), give it a try ;) 

PRs welcomed for Whisper

**Comment by merefield** [comment]
@alexrudall I just released a "chat bot" adaptor using your API a few hours ago: https://github.com/merefield/discourse-chatbot

I really appreciate you implementing the changes for the new API so fast, I'll try to make some time to convert it to `gpt-3.5-turbo` in the next few days.

**Comment by merefield** [comment]
And that's DONE FYI ... and working really nicely, thank you!

**Comment by Clemalfroy** [comment]
> ChatGPT is released in version [v3.4](https://rubygems.org/gems/ruby-openai/versions/3.4.0), give it a try ;)
> 
> PRs welcomed for Whisper

https://github.com/alexrudall/ruby-openai/pull/200

**Comment by alexrudall** [comment]
Whisper added in [v3.5](https://rubygems.org/gems/ruby-openai/versions/3.5.0), big thanks @Clemalfroy!
