### ISSUE TITLE
Readme whisper issue

### ISSUE THREAD

**Issue by Michael3434** [alexrudall/ruby-openai#205]
Hey! I Really like this gem, I was looking for whisper using ruby and I had to create a separate app with python but now it's there :) amazing! Thanks!

I saw on the readme there is this:

response = client.transcribe(
        parameters: {
            model: "whisper-1",
            file: File.open('path_to_file'),
        })
    puts response.**parsed_body**['text']
    => "Transcription of the text"
    
    "parsed_body" -> But I think it's "parsed_response"

**Comment by alexrudall** [comment]
Good spot! Fixed
