### ISSUE TITLE
Support for additional parameters?

### ISSUE THREAD

**Issue by merefield** [alexrudall/ruby-openai#208]
I don't believe this was covered explicitly in your documentation exactly, so just want to check.

If we want to pass an additional parameter, can we just add them as perhaps one would expect?

e.g. for adding `temperature` is this ok?:

```
        response = @client.chat(
          parameters: {
              model: "gpt-3.5-turbo",
              messages: messages,
              temperature: 0.7
          })
```

etc.

**Comment by alexrudall** [comment]
Hi buddy, yes you certainly can. I've tweaked the README to make this a bit clearer

**Comment by merefield** [comment]
You are a :star thanks!
