### ISSUE TITLE
Finetuning GTP3?

### ISSUE THREAD

**Issue by ohlhaver** [alexrudall/ruby-openai#226]
In the OpenAi documentation it says

`Fine-tuning is currently only available for the following base models: davinci, curie, babbage, and ada. These are the original models that do not have any instruction following training (like text-davinci-003 does for example). You are also able to [continue fine-tuning a fine-tuned model](https://platform.openai.com/docs/guides/fine-tuning/continue-fine-tuning-from-a-fine-tuned-model) to add additional data without having to start from scratch.`

However, when I use client.models.list it says `"allow_create_engine"=>false,` (my understanding was that that's the method for fine-tuning:) for all models and ` "allow_fine_tuning"=>true` only for the "snapperm-" models. What are those?

Am I missing something?

Thanks!

**Comment by alexrudall** [comment]
Hi @ohlhaver , sorry to hear you're having issues. OpenAI have [removed a few models recently](https://community.openai.com/t/the-model-text-davinci-edit-001-does-not-exist/116144) and I wonder if this is another victim. You might do better asking this question over on the OpenAI forum as I don't think this is an issue with `ruby-openai`

**Comment by bf4** [comment]
recommend closing this as invalid
