### ISSUE TITLE
Undefined method `completions' for #<OpenAI::Client:0x00007fe1a2e621a8>

### ISSUE THREAD

**Issue by PhilipAnd** [alexrudall/ruby-openai#24]
Thank for you for the time creating this Gem. When I try to test it out with an example I get the error:

`NoMethodError (undefined method `completions' for #<OpenAI::Client:0x00007fe1ab35e2d0>):`

When I unpack the gem the client.rb looks like: 
`module OpenAI
  class Client
    include HTTParty
    base_uri "https://api.openai.com"

    def initialize(access_token: nil)
      @access_token = access_token || ENV["OPENAI_ACCESS_TOKEN"]
    end

    def call(engine:, prompt:, max_tokens:, version: "v1")
      self.class.post(
        "/#{version}/engines/#{engine}/completions",
        headers: {
          "Content-Type" => "application/json",
          "Authorization" => "Bearer #{@access_token}"
        },
        body: {
          prompt: prompt, max_tokens: max_tokens
        }.to_json
      )
    end
  end
end
`

Could it be that the latest code hasn't been committed and can be retrieved by the gems?

**Comment by alexrudall** [comment]
Weird - seems OK for me on version 0.3.0. What version do you see when you do `bundle list`?

**Comment by PhilipAnd** [comment]
Thanks @alexrudall it worked! :)
