### ISSUE TITLE
Accessing to response headers and code in v4

### ISSUE THREAD

**Issue by dmitry** [alexrudall/ruby-openai#255]
**Is your feature request related to a problem? Please describe.**
In version 3 there was a possibility to access the response code. In the current version 4.0.0, it's not possible.

**Describe the solution you'd like**
It would be good to access the response headers and code. Sometimes openai API returns 429 response code. Need to be able to retry in 1 second once again. Now it's not possible to use a retry mechanism.

**Describe alternatives you've considered**
Stick with v3 for now, as v4 returns via `to_json` JSON hash.

**Comment by airblade** [comment]
The API uses [HTTP error codes](https://platform.openai.com/docs/guides/error-codes) with its responses to convey useful information.  It would be very helpful to be able to access them.

**Comment by alexrudall** [comment]
Good suggestion. We could add the option to pass `raw: true` or similar and that will return the raw responses instead. Would that work?

**Comment by airblade** [comment]
Sounds good to me.

**Comment by ScotterC** [comment]
+1 to this. It's particularly important when writing logic to handle retries and stay under rate limiting.

It looks like in [http](https://github.com/alexrudall/ruby-openai/blob/main/lib/openai/http.rb) that each request method is returning `body` if it's there. I'm guessing that passing each of these through a general `build_response` method to create a response object would be appropriate?

**Comment by kevingriffin** [comment]
It'd be great if error statuses actually resulted in exceptions being raised. Getting the raw response could be helpful sometimes, but ideally the error cases wouldn't seem to be normal responses until you went to parse them.

**Comment by thibaut-pro** [comment]
I'd love to upgrade to v5 to use the `rough_token_count` but this issue is a blocker for us.

> the option to pass `raw: true` or similar and that will return the raw responses instead.

☝️ That would work really well!

**Comment by ScotterC** [comment]
@alexrudall heres my solution to this that I've been running in production for 3+ months. If it looks good I can setup a PR. 
https://github.com/ScotterC/ruby-openai/blob/dewey/lib/openai/http.rb

`raw` is a Boolean parameter passed into json_post with other parameters. It determines whether to return the raw faraday response or not.

**Comment by cheiff** [comment]
Yes, please submit a PR with your patch. I've tested your code and works OK. This is what we need, too.
Thank you!

**Comment by codenamev** [comment]
> It'd be great if error statuses actually resulted in exceptions being raised. Getting the raw response could be helpful sometimes, but ideally the error cases wouldn't seem to be normal responses until you went to parse them.

I agree with this sentiment, and submitted another PR (#328) that resolves the specific error case.  I'm curious what folks are using the raw response object for (other than error handling)?  Just thinking there may be a use-case for both PRs 😄

**Comment by alexrudall** [comment]
Exception handling released in [v6](https://github.com/alexrudall/ruby-openai/releases/tag/v6.0.0) - I suspect the `raw` solution is no longer needed. Can reopen if it is.
