### ISSUE TITLE
No exception information returned in Stream mode

### ISSUE THREAD

**Issue by lingceng** [alexrudall/ruby-openai#256]
The api returns a JSON when error, eg. 

```
{
  "error": {
    "message": "'user_role' is not one of ['system', 'assistant', 'user'] - 'messages.0.role'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

I use following  code to fix

```
    def self.to_json_stream(user_proc:)

      proc do |chunk, overall_received_bytes, env|
        Rails.logger.debug("raw chunk: #{chunk}")

        if chunk.start_with?("data: {")
          chunk.each_line do |line|
            next unless line.start_with?("data: {")
            line.delete_prefix!("data: ")
            user_proc.call(JSON.parse(line))
          end
        elsif chunk.include?('"error": ')
          user_proc.call(JSON.parse(chunk))
        else
          Rails.logger.warn("unkown raw chunk: #{chunk}")
        end
      end
    end
```

**Comment by lingceng** [comment]
The stream data may be split, here is the complete solution: https://gist.github.com/lingceng/afd30be6e102442fa48abf175efe3f6a

Any one can help merge to the project.

@itsderek23 @obie

**Comment by harlantwood** [comment]
FYI I have an open PR to solve the same issue, using a different approach: https://github.com/alexrudall/ruby-openai/pull/275

**Comment by atesgoral** [comment]
I'm working on properly fixing these issues with #338 (and I'll follow up with a breaking change to raise actual exceptions)

**Comment by alexrudall** [comment]
Released in [v6](https://github.com/alexrudall/ruby-openai/releases/tag/v6.0.0)
