### ISSUE TITLE
Transcribe throwing exception, expecting UploadFile

### ISSUE THREAD

**Issue by chadwilken** [alexrudall/ruby-openai#259]
**Describe the bug**
When using V4.0.0 of the gem and attempting to pass a file to the `transcribe` it receives the response below. Downgrading to version 3.7.0 works as a workaround.

```ruby
{"error"=>{"message"=>"1 validation error for Request\nbody -> file\n  Expected UploadFile, received: <class 'str'> (type=value_error)", "type"=>"invalid_request_error", "param"=>nil, "code"=>nil}}
```

**To Reproduce**
1. Attempt to pass a file to the `transcribe` methods `file` parameter
2. See error above as the `response`

**Expected behavior**
It should allow the file to be passed to the service and not attempt to stringify it.

**Code**
```ruby
recording.audio.attachment.blob.open do |file|
  response = client.transcribe(parameters: { model: "whisper-1", file: file })
  recording.update(transcription: response.parsed_response['text'])
end
```

**Additional context**
It seems to be coming from https://github.com/alexrudall/ruby-openai/blob/main/lib/openai/http.rb#L84 as `StringIO`, `Tempfile` and others `is_a?(File)` is `false`.

**Comment by alexrudall** [comment]
Thanks for raising this, fixed by @codergeek121 in [v4.3.1](https://rubygems.org/gems/ruby-openai/versions/4.3.1)
