### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by p6002** [alexrudall/ruby-openai#261]
If there is no GUI, how to use this tool? 
Do I have to modify the code in notepad every time? Maybe it's just an intermediate tool and I should look for something more?

**Comment by alexrudall** [comment]
Well, what do you want to do? This is a software library that you can use to make it easier to use the programming language Ruby with the OpenAI API. If you want to build something in Ruby with OpenAI, this is probably the library for you. If not, maybe not :)
