### ISSUE TITLE
Streaming: callbacks

### ISSUE THREAD

**Issue by alexrudall** [alexrudall/ruby-openai#264]
**Is your feature request related to a problem? Please describe.**
- Problem: No way to respond to success and error when streaming

**Describe the solution you'd like**
Add new callbacks to stream:

- on_data
- on_success
- on_error

Would love feedback on this. Thanks!

**Comment by itsderek23** [comment]
This would be great. Right now I'm using a version of https://github.com/alexrudall/ruby-openai/issues/256 to handle errors.

**Comment by codenamev** [comment]
The OpenAI API includes a signal for when a "success" happens in the form of `finish_reason`.  I've been using a "Streamer" object that I pass to this gem's `stream` param:

```ruby
class OpenAiStreamer
  attr_reader :on_complete, :chunk, :content

  def initialize(on_complete: nil)
    @content = ""
    @on_complete = on_complete
    @completed = false
  end

  def call(chunk)
    return if @completed

    @chunk = chunk
    @content << (@chunk || {}).dig("choices", 0, "delta", "content")

    # do something with the chunk...

    if finish_reason.present?
      @completed = true
      on_complete.call(self)
      return chunk
    end
  end

  def finish_reason
    (@chunk || {}).dig("choices", 0, "finish_reason")
  end
end

def success_callback(streamer)
  puts "Completed chat: #{streamer.content}"
end

client = OpenAI::Client.new
client.chat(
  parameters: {
    model: "gpt-3.5-turbo",
    messages: [...],
    stream: OpenAiStreamer.new(on_complete: method(:success_callback))
  }
)
```

It has been helpful in chaining responses, but I see it more as a patch.  I'm not sure I'm sold on the interface, but it works 🤷

**Comment by alexrudall** [comment]
Exception handling released in [v6](https://github.com/alexrudall/ruby-openai/releases/tag/v6.0.0)
