### ISSUE TITLE
Streaming: Cancel stream

### ISSUE THREAD

**Issue by alexrudall** [alexrudall/ruby-openai#265]
**Is your feature request related to a problem? Please describe.**
- Problem: wasting tokens continuing to stream in background jobs when no longer needed

**Describe the solution you'd like**
- Make `conn` accessible in the `stream: callback` so that Faraday `#close` could be called whenever the stream needed to be cancelled

Would love feedback on this. Thanks!

**Comment by fearlessfrog** [comment]
I forked and tried passing in the connection to the stream: callback and calling ```conn.close``` on it, but no luck, in that it was ignored. I also tried passing the request and setting ```req.options.on_data = nil``` which worked but was pretty ugly as a ```NoMethodException``` raised within Faraday. I then asked at Faraday on what would be a better thing to do here or if a req.stream_close was worth pursuing as a PR there:

https://github.com/lostisland/faraday/issues/1501

The summary from that is the underlying adapter for HTTP doesn't honor the close at this point, so the easiest thing to do was just raise a custom exception in the proc. So for me this was was something like

```ruby
 def stream_proc(*)
    proc do |chunk|
       raise CancelStreamException.new if some_cancel_flag_via_redis_etc
```
..and then a ```rescue CancelStreamException``` in the calling ```ApplicationJob```. 

It is using exceptions as logic which doesn't smell great, but does work ok. This could be an accepted way to cancel streams if you want to close given no changes in Faraday.

Note: in doing this, it seems Faraday ~> 2.0 has the ```Env::env`` object to pass to the proc in ```to_json_stream: user_proc.call```, and although I didn't need it for this issue it might be a good way to get response status and headers back into the proc as a separate change.

**Comment by obie** [comment]
i wonder if `throw` accomplishes the same result?

**Comment by fearlessfrog** [comment]
Yes, a 
```ruby
    catch(:close) do
      response = client.chat(
      ...
```

..and..

```ruby
throw :close if some_cancel_flag_via_redis_etc
```
..works great and is better ruby. Thanks!

**Comment by obie** [comment]
Yeah I figured! And I don't think it incurs all the exception backtrace overhead and whatnot. Great little underused feature.

**Comment by alexrudall** [comment]
Nice solution! Don't think there's a way to include this at the ruby-openai level so closing for now.
