### ISSUE TITLE
Token-count integration

### ISSUE THREAD

**Issue by jamiemccarthy** [alexrudall/ruby-openai#291]
Currently `ruby-openai` has no functionality for dealing with token counts. This is unfortunate because they do play a significant role in OpenAI's API. My app that uses it would benefit from built-in tools that count tokens in an integrated way.

I propose three improvements, which build on each other:

1. Add an `OpenAI::Client#token_count(parameters)` method, which returns two integers: the total number of OpenAI tokens in the parameters' messages, and the max number of tokens (input and output) for the parameter's model. Initially this would simply use [OpenAI's rules of thumb](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them) to estimate the count, based on character count and word count.
2. As a feature upgrade, `token_count` could check whether the module `::Tiktoken` is defined, and if so use Tiktoken's `.encode.length`, otherwise fall back on the rule-of-thumb estimate. (Since the relevant model is defined in `parameters`, we wouldn't have to guess which encoding to use.)
3. Have `json_post` `raise` a custom exception if the `token_count` for a request does not leave enough tokens for a meaningful response (say, a default of >= 10 tokens). The idea here is to avoid paying to send OpenAI messages it can't fulfill. This would probably include a new initialization option for `OpenAI::Client` to enable this behavior, that initially defaults to not `raise`-ing, but (if y'all find it useful) it might default to `raise`-ing in a future version. Maybe the `parameters` argument could have a new field added that overrides the minimum required token overhead.

I would make use of this functionality in my own app by writing a wrapper around `OpenAI::Client#chat` that instead of one model takes an Array, and tries to `#chat` with each in turn until it finds one that doesn't `raise`. If all 3 of the above were done, the wrapper would be just a couple of lines long. I figure that functionality might be specific enough to myself that it wouldn't be appropriate to add it to the gem, but if y'all are interested, it's possible.

Of course all this can be done manually, but since this gem is targeted at OpenAI, including this functionality seems like a natural fit to me. I've looked for work similar to this but haven't seen any.

**Comment by marckohlbrugge** [comment]
Hitting the token limit is one of the most common issues I run into. Some more functionality around this would be very useful 👍

**Comment by EthanMarrs** [comment]
I would find 1. and 2. useful 😄 I've implemented a very basic rule of thumb calculation for my apps, but a more accurate option would be useful in specific cases.

**Comment by jamiemccarthy** [comment]
Anyone have an opinion on the method returning two integers vs. writing two methods that each return one integer? When I only want one value, I don't mind writing `count, _ = client.token_count(...)`, but maybe others find that ugly?

**Comment by marckohlbrugge** [comment]
I’d split it up into two separate methods. That seems more Ruby-like and is less likely to confuse people unfamiliar with the above syntax.

**Comment by codenamev** [comment]
I've been using [toktoken_ruby gem](https://github.com/IAPark/tiktoken_ruby) and works great.  Would this be an acceptable dependency addition to provide a helper to this lib?

**Comment by jamiemccarthy** [comment]
> I've been using [toktoken_ruby gem](https://github.com/IAPark/tiktoken_ruby) and works great. Would this be an acceptable dependency addition to provide a helper to this lib?

What I'll do is check whether [the `::Tiktoken` module](https://github.com/IAPark/tiktoken_ruby/blob/main/lib/tiktoken_ruby.rb#L13) is defined, and if it is, use that.

That sidesteps the question. An app that prefers not to require Tiktoken doesn't have to, but one that does require it gets the benefit. It'll be up to each app.

**Comment by jamiemccarthy** [comment]
I've just submitted a PR for this, #306 .

**Comment by alexrudall** [comment]
@jamiemccarthy released in [v5.1](https://rubygems.org/gems/ruby-openai/versions/5.1.0), thanks for your work on this!!
