### ISSUE TITLE
Deprecation of v1/completions endpoint

### ISSUE THREAD

**Issue by chasemcdo** [alexrudall/ruby-openai#296]
**Is your feature request related to a problem? Please describe.**
In January the v1/completions endpoint will be deprecated: https://platform.openai.com/docs/deprecations

**Describe the solution you'd like**
Enable completion with gpt-3.5+ based models

**Additional context**
With the upcoming deprecation of endpoints that this package is reliant on for completion, it is approaching the time where we should consider enabling completion with non-deprecated models.

**Comment by alexrudall** [comment]
Thanks @chasemcdo - Completions endpoint removed in [v6](https://github.com/alexrudall/ruby-openai/releases/tag/v6.0.0)
