### ISSUE TITLE
Documentation of error codes

### ISSUE THREAD

**Issue by Pe-co** [alexrudall/ruby-openai#308]
I use the OpenAI::Client chat function with the gpt-4-0314 model, and will occasionally get rate_limit_exceeded and context_length_exceeded errors. Is there any documentation of the possible error codes I can get? 

The codes does not match the [error-codes](https://platform.openai.com/docs/guides/error-codes) listed in the openai docs

**Comment by Pe-co** [comment]
This seems to be an open-ai issue, not a ruby-openai issue, so I'm closing my own issue, sorry for the noise. 

This thread seems related
https://community.openai.com/t/api-error-codes-in-json-response-not-http-status/298219

**Comment by alexrudall** [comment]
@Pe-co OK interesting. No problem 🙏
