### ISSUE TITLE
Add new fine_tuning/jobs endpoints!

### ISSUE THREAD

**Issue by alexrudall** [alexrudall/ruby-openai#315]
[https://platform.openai.com/docs/api-reference/fine-tuning/create](https://platform.openai.com/docs/api-reference/fine-tuning/create)

**Comment by lancecarlson** [comment]
I made a PR for this https://github.com/alexrudall/ruby-openai/pull/316

**Comment by lancecarlson** [comment]
I added a list endpoint and renamed the current list to list_events because that is more accurate. It is an undocumented endpoint that I found in the python client library, so I mimicked what they were doing. There is some pagination functionality in there as well but maybe that can come later.

**Comment by alexrudall** [comment]
Thanks @lancecarlson! Released in [v6](https://github.com/alexrudall/ruby-openai/releases/tag/v6.0.0)
