### ISSUE TITLE
Provide a way to hook into logging for this gem

### ISSUE THREAD

**Issue by codenamev** [alexrudall/ruby-openai#320]
**Is your feature request related to a problem? Please describe.**
A common pattern for gems is to provide a configurable logger that can be used throughout the library to broadcast useful information.  An [example of the need here](https://github.com/alexrudall/ruby-openai/pull/270/files#diff-b944e7fce4884db7a0639a637f10d5a081ca198b280570d874865ee773a6bc09R57).

**Describe the solution you'd like**
Ideally, a `logger` method be added to the root namespace so it can be accessed from any part of the library.  The `logger` would return an instance of Ruby's `Logger` class (or a descendent), and this would be configurable within `OpenAI.configure`

**Comment by alexrudall** [comment]
Thanks @codenamev, [v6.3](https://github.com/alexrudall/ruby-openai/releases/tag/v6.3.0) adds a way to add a logger via Faraday's middleware - see [README](https://github.com/alexrudall/ruby-openai#verbose-logging)
