### ISSUE TITLE
example using completion api with GTP-4 models

### ISSUE THREAD

**Issue by juanviamonte** [alexrudall/ruby-openai#322]
When using:

```
response = ai_client.completions(
        parameters: {
            model: "gpt-4",
            prompt: "Whats 2+2 ?",
        })
```

response is: 
```
{"error"=>
  {"message"=>"This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
   "type"=>"invalid_request_error",
   "param"=>"model",
   "code"=>nil}}
```

not sure if this is an issue

**Comment by koenhandekyn** [comment]
fighting same question, how can we do completions api ?

**Comment by alexrudall** [comment]
[Completions endpoint is deprecated](https://openai.com/blog/gpt-4-api-general-availability) and removed in [v6](https://github.com/alexrudall/ruby-openai/releases/tag/v6.0.0) - use the Chat API instead.
