### ISSUE TITLE
Chat stream controller

### ISSUE THREAD

**Issue by PsiKai** [alexrudall/ruby-openai#324]
**Is your feature request related to a problem? Please describe.**

I am not seeing a way to signal to the stream that I want to abort, for the cases of when a response is getting too long, or is wrong and I want to start over.

In the [node package](https://www.npmjs.com/package/openai) for the OpenAI API, they expose a `controller` object which allows you to abort the stream midway through.

**Describe the solution you'd like**

I would like that calling the `chat` method on a client instance would return a stream controller so that I can abort the stream if need be.  Perhaps this is already possible with how you built it, but I did not have success attempting to use it.  If this is already possible, would you please update the readme with instructions?

Example usage:

```rb
@chat_stream = client.chat(parameters:)

...

@chat_stream.controller.abort
```

**Additional context**

Node.js implementation:

<img width="771" alt="Screenshot 2023-09-01 at 2 39 20 PM" src="https://github.com/alexrudall/ruby-openai/assets/63161310/2a6b105d-4ad7-40fa-8341-1efb12b2b0a1">

----

Thank you for providing and maintaining this Gem 🙏

**Comment by alexrudall** [comment]
This would be cool and a well used feature I think, definitely open to a PR on it

**Comment by coezbek** [comment]
As per discussion in the past (#265), one way to abort is to raise an exception from the proc.
