### ISSUE TITLE
Set extra headers for a chat

### ISSUE THREAD

**Issue by javereec** [alexrudall/ruby-openai#333]
Helicone has this feature were you can group requests, which can be really helpful to calculate unit economics (e.g. what is the cost of this conversation).

If we take the code below, 

```
  OpenAI::Client.new.chat(
      parameters: {
        model: 'gpt-3.5-turbo',
        messages: Message.for_openai(trip.messages),
        temperature: 0.1,
        stream: stream_proc(message:)
      }
    )
  end
```

I was thinking that it would be helpful to have an optional param (e.g. `extra_headers`) that is merged into the headers already set when initialising the gem. The result would look something like

```
  OpenAI::Client.new.chat(
      parameters: {
        model: 'gpt-3.5-turbo',
        messages: Message.for_openai(trip.messages),
        temperature: 0.1,
        stream: stream_proc(message:)
      },
      extra_headers: {
        'Helicone-Property-Conversation': 'conversation-123'
      }
    )
  end
```

**Comment by alexrudall** [comment]
Thanks @javereec - I'd prefer to include it in `parameters` and handle it in `json_post` - that way it could be added to any `post` request.

```
  OpenAI::Client.new.chat(
      parameters: {
        model: 'gpt-3.5-turbo',
        messages: Message.for_openai(trip.messages),
        temperature: 0.1,
        stream: stream_proc(message:),
        extra_headers: {
          'Helicone-Property-Conversation': 'conversation-123'
        }
      }
    )
  end
```
```
    def json_post(path:, parameters:)
      to_json(conn.post(uri(path: path)) do |req|
        if parameters[:stream].respond_to?(:call)
          req.options.on_data = to_json_stream(user_proc: parameters[:stream])
          parameters[:stream] = true # Necessary to tell OpenAI to stream.
        elsif parameters[:stream]
          raise ArgumentError, "The stream parameter must be a Proc or have a #call method"
        end

        req.headers = headers(extra_headers: parameters[:extra_headers])
        req.body = parameters.to_json
      end&.body)
    end
```
```
    def headers(extra_headers:)
      if azure?
        azure_headers
      else
        openai_headers
      end.merge(@extra_headers || {}).merge(extra_headers || {})
    end
```

Would welcome a PR on this with a simple spec (in `http_spec.rb`)

**Comment by deikka** [comment]
Hi! I'm hands on with the PR. Probably dumb question: How do I get last request headers in the spec? Webmock?

**Comment by alexrudall** [comment]
Thanks @deikka! Sorry if I don't understand - the suite uses VCR to record responses. If you add an OPENAI_ACCESS_TOKEN to in a .env file it will record new responses. You can just run one spec and see the changed response in git.

**Comment by deikka** [comment]
ok! Maybe something like this could work? 

describe 'extra_headers' do
  it 'adds the extra headers to the request' do
    client = OpenAI::Client.new
    extra_headers = { 'Helicone-Property-Conversation': 'conversation-123' }
    VCR.use_cassette('chat') do
      response = client.chat(parameters: { model: 'gpt-3.5-turbo', messages: [], temperature: 0.1, extra_headers: extra_headers })
    end

    request_headers = VCR.current_cassette&.http_interactions&.last&.request&.headers

    expect(request_headers).to include(extra_headers)
  end
end

**Comment by alexrudall** [comment]
Ah just realised what this is referring to sorry. Could possibly use `expect(c2).to receive(:get).with(path: "/files").once` style so actually wouldn't need VCR.

**Comment by deikka** [comment]
Ah, ok. I'll send the PR and there we can comment. thnks!

**Comment by alexrudall** [comment]
Sounds good!

**Comment by alexrudall** [comment]
This is now possible: [see here](https://github.com/alexrudall/ruby-openai#extra-headers-per-client)
