### ISSUE TITLE
Getting result after stream completed

### ISSUE THREAD

**Issue by avdept** [alexrudall/ruby-openai#334]
**Is your feature request related to a problem? Please describe.**
So, now when you're using streaming feature after its over there's no information provided as a result of method invoke. Here's the example

```
@client = OpenAI::Client.new(access_token: 'myToken')
@response = @client.chat(
      parameters: {
        model: 'gpt-3.5-turbo-16k', # Required.
        messages: [*messages],
      stream: proc do |chunk, _bytesize|
        doSomething(chunk)
      end
})

puts @response
=> []
```
Its not returning errors either, but there's open PR to fix that. But it also doesnt have any information about tokens user or anything else returned by openAi api.

**Describe the solution you'd like**
I'd want `@response` object to behave same way for stream/non stream types of request

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by avdept** [comment]
Ok, I did a bit of debugging and seems like it's the `Faraday` gem issue. Nothing comes in response. Closing as not relevant to this gem

**Comment by alexrudall** [comment]
Thanks for following up!
