### ISSUE TITLE
When using model 'gpt-4' uses gpt-4-0613 (snapshot)

### ISSUE THREAD

**Issue by Pascaltib** [alexrudall/ruby-openai#341]
**Describe the bug**
When setting the model to 'gpt-4' uses 'gpt-4-0613' by default.

**To Reproduce**
`client.chat(
      parameters: {
        model: 'gpt-4',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.8
      }
    )`

**Expected behavior**
I would assume it uses gpt-4 which gets updated and not a version which will be deprecated at some point.

**Output**
`{"id"=>"chatcmpl-8B3rNryeXag8Vp0EFJJJ7z2PQR61w", "object"=>"chat.completion", "created"=>1697647137, "model"=>"gpt-4-0613", "choices"=>[{"index"=>0, "message"=>{"role"=>"assistant", "content"=>"\"Cracking the Culture Code: A Fresh Perspective on Teaching Math Critically\""}, "finish_reason"=>"stop"}], "usage"=>{"prompt_tokens"=>199, "completion_tokens"=>16, "total_tokens"=>215}}`

**Desktop (please complete the following information):**
 - OS: Mac M1

**Comment by Pascaltib** [comment]
When you list the models you can see there are 3 gpt-4 ones:
gpt-4-0314
gpt-4-0613
gpt-4

**Comment by jtoy** [comment]
i thought using gpt-4 automatically  uses the latest gpt-4 on the openai side?!

**Comment by Velora** [comment]
I believe this is working as expected and as you want.

Setting "gpt-4" means you want to use the current version of the "gpt-4" model, which is "gpt-4-0613". 

If OpenAI updated the current default today to gpt-4-1022, for example, then using "gpt-4" would start referencing that. 

So unless you explicitly write in "gpt-4-0613" to lock to that model, your calls with "gpt-4" will use the latest model available. 

There is no "gpt-4" model, only "gpt-4-0314" and "gpt-4-0613".

**Comment by alexrudall** [comment]
Added a note to cover this in the README

```
#### Examples

- [GPT-4 (limited beta)](https://platform.openai.com/docs/models/gpt-4)
  - gpt-4 (uses current version)
  - gpt-4-0314
  - gpt-4-32k
...
```
