### ISSUE TITLE
HTTP responses without a JSON body will raise JSON parser exceptions

### ISSUE THREAD

**Issue by atesgoral** [alexrudall/ruby-openai#357]
**Describe the bug**
With #344 there's an oversight: When the OpenAI fetch fails without a JSON error in the body, it will still result in an error being raised, but it will be a JSON parse exception.

**To Reproduce**
Tweak spec/fixtures/cassettes/gpt-3_5-turbo_streamed_chat_with_error_response.yml to return a 500 and remove the `body` (or make it invalid JSON).

**Expected behavior**
A Faraday Internal Server Error should be raised with the original response body.

**Additional context**
I broke this. I'm fixing it. PR incoming soon.

**Comment by alexrudall** [comment]
Thank you @atesgoral ya legend, released in [6.0.1](https://github.com/alexrudall/ruby-openai/releases)

**Comment by atesgoral** [comment]
@alexrudall Thanks for the quick release!
