### ISSUE TITLE
More verbose logging needed for Faraday Errors

### ISSUE THREAD

**Issue by alexrudall** [alexrudall/ruby-openai#365]
**Is your feature request related to a problem? Please describe.**
Faraday Errors in logs just show up like Faraday::BadRequestError (the server responded with status 400), which is not very helpful for debugging!

**Describe the solution you'd like**
Faraday has the ability to spit out more verbose logs I think. Maybe Faraday options should be customisable in config

**Comment by harlantwood** [comment]
This is super important for us too 👍  

The error message we care about is normally in the response body, which is JSON with a top level `error` key, eg:

```
curl -v https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer [REDACTED]" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "systemMMM",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "stream": true
  }'

[snip]
< HTTP/2 400 
< content-type: application/json
[snip]
{
  "error": {
    "message": "'systemMMM' is not one of ['system', 'assistant', 'user', 'function'] - 'messages.0.role'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by alexrudall** [comment]
Thanks @harlantwood , currently you can do 

```
  begin
    OpenAI::Client.new.models.retrieve(id: "text-ada-001")
  rescue Faraday::Error => e
    raise "Got a Faraday error: #{e}"
  end
```

does that help in your usecase?

Alternatively, here's PR for adding a Logger (plus any other middleware): https://github.com/alexrudall/ruby-openai/pull/373

**Comment by harlantwood** [comment]
Hmm for our usecase I am less interested in logging errors, more interested in acting on errors in specific cases, where we can tell something useful to the user, and in other cases, re-throwing the exception to be handled by our error reporting service.

So something like this should work for us:

```rb
begin
  # openai call….
rescue Faraday::BadRequestError => e
  response_body = e.response[:body]
  # if response body is “exceeded context length” then let the user know
  # else Sentry.handle_exception(e, extra: { response _body: })
end
```

I wonder if there is a way to put this error handling into the middleware.. but this should work!

**Comment by harlantwood** [comment]
Hmm maybe the library could wrap these Faraday errors, so the user could do:

```rb
begin
  # openai call….
rescue OpenAI::Error => e
  # e.message => “exceeded context length”   # the message body from OpenAI, ie the useful information
  # e.cause => the original Faraday::Error  # so that we don't loose access to the internal error, for advanced cases
end
```

This seems like it would address both the logging use case and the error service usecase, by putting the relevant details up front in the message.

* Docs on `Exception#cause`: https://ruby-doc.org/3.2.2/Exception.html#method-i-cause
