### ISSUE TITLE
Need documentation for the Assistants, Threads, Messages & Runs endpoints!

### ISSUE THREAD

**Issue by alexrudall** [alexrudall/ruby-openai#376]
- These endpoints need to be added to the README
- Each endpoint should have a simple copy-paste example

**Comment by hsztan** [comment]
Hi @alexrudall. Where can I find documentation or examples for the assistants | threads | message | runs workflows? 😎

**Comment by PetrosKalafatidis** [comment]
I can help you to add these examples on the README

**Comment by alexrudall** [comment]
> I can help you to add these examples on the README

I'd really appreciate a PR on this @PetrosKalafatidis ! Thank you! Following the style of the existing README, with examples that can just be copy pasted and work.

**Comment by alexrudall** [comment]
Shout out to @coezbek for adding Assistants docs! 3 more to go:

- [x] Assistants
- [ ] Threads
- [ ] Messages
- [ ] Runs

**Comment by coezbek** [comment]
I have some work in progress on Threads and Messages, but am lacking some testing on using the function call tool:

https://github.com/alexrudall/ruby-openai/compare/main...coezbek:ruby-openai:coezbek-readme-assistant

Hope to have it done in the next couple of days.

**Comment by alexrudall** [comment]
Legend!

**Comment by coezbek** [comment]
Done in PR #404

**Comment by BassamAziz** [comment]
hey guys, is the assistants api working for you?
I'm getting undefined method error. ` undefined method `assistants' for #<OpenAI::Client:0x00007fb03182d7d0 @models=#<OpenAI::Models:0x00007fb02f31c590>> `
and from the official doc, it says add the beta header, but i also get undefined method for the .add_headers method
any clue?

Thanks,
Bassam

**Comment by isasi88** [comment]
Hi @BassamAziz, I'm having the same problem. Any fix?

**Comment by alexrudall** [comment]
@BassamAziz @isasi88 I'm guessing you were on an older version of the library? If still an issue, let me know.
