### ISSUE TITLE
JSON mode

### ISSUE THREAD

**Issue by andrius** [alexrudall/ruby-openai#377]
Actually this is not a bug. I want to get a plain JSON from the OpenAI, recently they have introduced the JSON mode: https://platform.openai.com/docs/guides/text-generation/json-mode

It is possible to call it somehow?

**Comment by alexrudall** [comment]
Hello, sure is

```
response = client.chat(
    parameters: {
        model: "gpt-3.5-turbo", 
        response_format: { type: "json_object" },
        messages: [{ role: "user", content: "Hello!"}],
        temperature: 0.7,
    })
```

**Comment by alexrudall** [comment]
Added it to the README [https://github.com/alexrudall/ruby-openai#json-mode](https://github.com/alexrudall/ruby-openai#json-mode)

**Comment by jikkuatwork** [comment]
Recently groq too added, but when I give the option it fails! Any ideas?
