### ISSUE TITLE
How can we add parameters to the OpenAI::Messages list call

### ISSUE THREAD

**Issue by mibock** [alexrudall/ruby-openai#380]
The list messages call in the OpenAI API takes some optional parameters like limit, order, after and before.
It would be good to be able to pass these in:
def list(thread_id:)
   @client.get(path: "/threads/#{thread_id}/messages")
end
---->
def list(thread_id:, parameters: {})
   @client.get(path: "/threads/#{thread_id}/messages").  (TODO add the parameters)
end
Thanks

**Comment by chuducandev** [comment]
Agreed. I see the current list messages function always returns the first 20 messages in the thread and there are almost no ways to retrieve the latest message of a thread.

**Comment by davidpenso** [comment]
Do we know when this PR will be merged https://github.com/alexrudall/ruby-openai/pull/388 ?

**Comment by davidpenso** [comment]
Any luck merging this https://github.com/alexrudall/ruby-openai/pull/388? @alexrudall 

> I can merge this weekend :)

**Comment by alexrudall** [comment]
OK THIS weekend ;) Released in [v7](https://github.com/alexrudall/ruby-openai/releases/tag/v7.0.0)
