### ISSUE TITLE
Please re-add support for completions API

### ISSUE THREAD

**Issue by jimkleban** [alexrudall/ruby-openai#381]
**Is your feature request related to a problem? Please describe.**
Yes, deprecated models such as text-davinci-003 and not deprecated models such as gpt-3.5-turbo-instruct are compatible with legacy Completions endpoint and not Chat Completions.

Request is to re-add completions until there are no longer any supported models that use these.
 
**Describe the solution you'd like**
Re-add completions as it was.

**Describe alternatives you've considered**
Not using this gem :(

**Comment by alexrudall** [comment]
Sorry to hear this has negatively affected you - are you aware that these models will be [removed on 4 Jan](https://platform.openai.com/docs/deprecations)? Could you use version 5.2 of ruby-openai until then?

**Comment by JakeHendrick** [comment]
Based on that [deprecation doc](https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings) it appears that some old models were deprecated and a new one is available (ie. `gpt-3.5-turbo-instruct`).

The new model is still compatible with completions endpoint which is not deprecated (yet):
https://platform.openai.com/docs/models/gpt-3-5
> gpt-3.5-turbo-instruct: Similar capabilities as text-davinci-003 but compatible with legacy Completions endpoint and not Chat Completions.

I would also request maintaining support for the completions endpoint while there are still non-deprecated models available for it.

**Comment by jimkleban** [comment]
Yes, thanks I am using 5.2 and my request for completions API is for gpt-3.5-turbo-instruct

**Comment by moeSizlak** [comment]
Agreed.  It's not possible to use gpt-3.5-turbo-instruct without the completions endpoint.  Please re-add completions!

**Comment by alexrudall** [comment]
Will try to re-add this weekend.

**Comment by mishranant** [comment]
@alexrudall request you to merge my PR resolving this issue https://github.com/alexrudall/ruby-openai/pull/444

**Comment by alexrudall** [comment]
Apologies for the delay, added back in [v6.5](https://github.com/alexrudall/ruby-openai/releases/tag/v6.5.0)
