### ISSUE TITLE
completions undefined

### ISSUE THREAD

**Issue by renatomserra** [alexrudall/ruby-openai#387]
Latest version client.completions isnt working, says method undefined by client :) Downgrading fixed it

**Comment by fussy113** [comment]
`completions` scheduled to be deprecated.
We can use `chat` method instead of it.

https://github.com/alexrudall/ruby-openai/blob/f9046a317294ade235c211a34cbb103a965a5e80/lib/openai/client.rb#L25-L27

https://github.com/alexrudall/ruby-openai/pull/350

**Comment by ZeroMax-dev** [comment]
OpenAI has new Instruct models now, namely gpt-3.5-turbo-instruct. This model cannot be called via chat but needs to be called via the completions API. Can we bring it back, pls?

**Comment by alexrudall** [comment]
@ZeroMax-dev @renatomserra it's back in [v6.5](https://github.com/alexrudall/ruby-openai/releases/tag/v6.5.0), thanks for flagging
