### ISSUE TITLE
Thread list not showing 

### ISSUE THREAD

**Issue by capjuancode** [alexrudall/ruby-openai#390]
**Describe the bug**
``` ruby 
client = OpenAI::Client.new
client.threads.list
```
>irb(main):015> client.threads.list

>OpenAI HTTP Error (spotted in ruby-openai 6.3.0): {"error"=>{"message"=>"Your request to GET /v1/threads must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.", "type"=>"invalid_request_error", "param"=>nil, "code"=>"missing_scope"}}
/Users/juanlopez/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.12/lib/faraday/response/raise_error.rb:18:in `on_complete': the server responded with status 401 (Faraday::UnauthorizedError)

**To Reproduce**
1. Go to: `rails console`
2. connect to openAi client: `client = OpenAI::Client.new`
3. Type on console(bug): `client.threads.list` 

**Expected behavior**
See list of treads...

**Comment by capjuancode** [comment]
Interesting the api documentation does not have a list call

**Comment by coezbek** [comment]
Seems like there is no way to list threads from the API unless you have an id already.

**Comment by capjuancode** [comment]
@coezbek 
> Seems like there is no way to list threads from the API unless you have an id already.

Do you mean messages? 

and yes I had to start storing thread id's to manage this...

**Comment by coezbek** [comment]
No, messages you can list via the messages end-points.

**Comment by alexrudall** [comment]
Released in [v6.4](https://github.com/alexrudall/ruby-openai/releases/tag/v6.4.0)
