### ISSUE TITLE
Missing parameters for get request on list messages.

### ISSUE THREAD

**Issue by jejacks0n** [alexrudall/ruby-openai#407]
On the [List Messages](https://platform.openai.com/docs/api-reference/messages/listMessages) beta endpoint there's some new (I think added within the last week or two) pagination logic.

This requires some query params on the request, but there's not a way to add those currently. I monkeypatched it so I can continue testing, but I'd be happy to open a PR with a larger fix if that's worth doing.

Is there a way you'd like for me to approach this in general, and if so, how? Here's my quick and dirty code using the `ActiveSupport` `Hash#to_query` method.

```ruby
module OpenAI
  class Messages
    # Add parameters to the list method.
    def list(thread_id:, parameters: {})
      query = parameters.present? ? "?#{parameters.to_query}" : ""
      @client.get(path: "/threads/#{thread_id}/messages#{query}")
    end
  end
end
```

**Comment by alexrudall** [comment]
Definitely open to a PR on this, thanks. Generally I prefer code that's

- Simple
- Reusable (eg if there are other endpoints that have pagination)
- Works by default - the less config / setup users have to do the better
- Easy to understand, especially in how to use it
- Documented (in the README)
- Written so a junior developer can understand it and use it

Thanks a lot!

**Comment by alexrudall** [comment]
Released in [v7](https://github.com/alexrudall/ruby-openai/releases/tag/v7.0.0)
