### ISSUE TITLE
function calls documentation -> functions are "deprecated" and replaced by tools

### ISSUE THREAD

**Issue by madeleine-neumann-9e** [alexrudall/ruby-openai#429]
Hey  everyone, 

I tried to implement function calls and it took me some time to figure out, that your documentation about that is a little bit outdated. 

You're refering to "functions" but functions will now be handled by "tools" -> https://platform.openai.com/docs/assistants/tools/function-calling

**Comment by courtsimas** [comment]
probably worth submitting a PR and updating it
