### ISSUE TITLE
Configure maximum length

### ISSUE THREAD

**Issue by eslamodeh** [alexrudall/ruby-openai#433]
Hey everyone 👋 

In Chat GPT UI, you can configure the maximum length / token the model(assistance) should return. Is it possible to configure this at the moment?

![image](https://github.com/alexrudall/ruby-openai/assets/41170621/861cb6fb-e048-420e-9520-bfe58f7951d3)

**Comment by MyklClason** [comment]
Fairly sure this is "max_tokens" as per the API Docs and seems to work fine.

https://platform.openai.com/docs/api-reference/chat/create

**Comment by eslamodeh** [comment]
Thanks @MyklClason

Is this configurable in this SDK?

**Comment by MyklClason** [comment]
P.S. That model isn't the one you want to be using, so make sure to update that.

**Comment by alexrudall** [comment]
Thanks for the question @eslamodeh and the answer @MyklClason !
