### ISSUE TITLE
Ability to suppress stdout error logging

### ISSUE THREAD

**Issue by key88sf** [alexrudall/ruby-openai#437]
**Is your feature request related to a problem? Please describe.**
When OpenAI returns an error, there is always a stdout log message written by the gem.
https://github.com/alexrudall/ruby-openai/blob/7666e3084bcc6c10e0fd350224db874d07bbfd55/lib/openai.rb#L30

There doesn't seem to be any way to suppress these.

**Describe the solution you'd like**
A configuration option to NOT write these log messages.

**Comment by alexrudall** [comment]
Released in [v7](https://github.com/alexrudall/ruby-openai/releases/tag/v7.0.0) - the default will now NOT log errors to stdout, the new `log_errors` config will reenable if needed
