### ISSUE TITLE
{} is not of type 'boolean' - 'stream'

### ISSUE THREAD

**Issue by juanviamonte** [alexrudall/ruby-openai#440]
@alexrudall love your gem and the amazing work you've been doing here!, everything works amazingly, I'm having this small issue with Streams that I'm not sure if is related to something missing in the docs or the latest version code  Super appreciate your help beforehand.

**Describe the bug**

Getting the following error when trying to use the stream argument

```
{"error"=>{"message"=>"{} is not of type 'boolean' - 'stream'", "type"=>"invalid_request_error", "param"=>nil, "code"=>nil}}
```

**To Reproduce**
1. I have the gem in the gemfile listed as `gem "ruby-openai"` in the Gemfile.lock list version `ruby-openai (3.7.0)`
2.  Example code

```
client = OpenAI::Client.new(access_token: access_token, request_timeout: 360)
client.chat(
        parameters: {
          model: "gpt-4-0125-preview",
          messages: [{ role: "user", content: "Describe a character called Anna!" }],
          temperature: 0.7,
          stream: proc do |chunk, _bytesize|
            puts chunk
          end
        }
      )

```

Getting similar behavior while following this example https://gist.github.com/alexrudall/cb5ee1e109353ef358adb4e66631799d 

**Expected behavior**
Stream should return answers from OpenAI

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 (23C71) [Sonoma] | Intel UHD Graphics 630 1536 MB 

**Additional context**

<img width="1414" alt="image" src="https://github.com/alexrudall/ruby-openai/assets/85184407/7269f502-e966-4d41-8e7b-8d6a29c13b32">

**Comment by alexrudall** [comment]
Thanks @juanviamonte -- looks like you are using an old version of ruby-openai - [upgrade to 4.0+](https://github.com/alexrudall/ruby-openai/releases/tag/v4.0.0) to get the ability to stream chat responses :)
