### ISSUE TITLE
Include an image in a message into a thread

### ISSUE THREAD

**Issue by leandrosardi** [alexrudall/ruby-openai#443]
I want to create and run a message into a thread, including the URL to an image.

Is it possible to do something like this in the current version?

Example:

```ruby
            mid = @@openai_client.messages.create(
                'thread_id': @@openai_thread_id,
                'parameters': {
                    'role': "user", # Required for manually created messages
                    'content': "What do you see in this picture?", # Required.
                    'image_url': 'https://static.vecteezy.com/system/resources/thumbnails/039/391/155/small/500-social-media-stories-v2-abstract-shopping-nft-e-commerce-memories-bundle.png',
                },
            )["id"]

            @@openai_message_ids << mid

            # run the assistant
            response = @@openai_client.runs.create(
                thread_id: @@openai_thread_id,
                parameters: {
                    assistant_id: @@openai_assistant_id,
                }
            )
            run_id = response['id']
```

**Comment by willywg** [comment]
If you are referring to GPT-4 with vision, it's currently not possible with the Assistant API. However, you can use it with the Chat Completions API.

See: https://platform.openai.com/docs/guides/vision

> Plese note that the Assistants API does not currently support image inputs.

**Comment by willywg** [comment]
@leandrosardi now it's possible. Look at this: https://platform.openai.com/docs/assistants/how-it-works/creating-image-input-content

**Comment by leandrosardi** [comment]
> @leandrosardi now it's possible. Look at this: https://platform.openai.com/docs/assistants/how-it-works/creating-image-input-content

Hello @willywg. Thank you for your comments, and my apologies for my late response.

I am resuming this project, and I am checking the latest link you posted here.

**Comment by ausangshukla** [comment]
I want to do exactly the same thing, is there an example of how to do it with the gem ? Thanks

**Comment by alexrudall** [comment]
Thanks for this @leandrosardi & @willywg. @ausangshukla, I've added an example to the README [here](https://github.com/alexrudall/ruby-openai?tab=readme-ov-file#vision-in-a-thread).
