### ISSUE TITLE
client.files.content(id: "file-123") failing for image_files because of JSON parse

### ISSUE THREAD

**Issue by Lasvad** [alexrudall/ruby-openai#450]
**Describe the bug**
Reading files such as pngs that are generated by code interpreter seem to fail as the response is expected to be JSON

Doc reference this to read file content: `client.files.content(id: "file-123")`

example

Code interpreter returns... 
```
"content"=>
  [{"type"=>"image_file", "image_file"=>{"file_id"=>"file-stub"}},
   {"type"=>"text",
    "text"=>
     {"value"=>
```

using the cmd
```
client.files.content(id: "file-stub")
```

returns
```
(JSON::ParserError)s/ruby-3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse': unexpected token at '\x89PNG
```

I've tried to use File.write, TempFile, StringIO but the JSON parse error continues. 

**To Reproduce**
1. Use Assistant to create a png with code interpreter 
2. Try to read the file_id that is provided in the response
3. Error shows when using `client.files.content(id: "file-123")`

**Expected behavior**
Need a way to parse image_files files from OpenAI

**Screenshots**
<img width="1272" alt="image" src="https://github.com/alexrudall/ruby-openai/assets/9116207/20e85019-cc08-41aa-aa94-aac575261e2c">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser N/A

**Additional context**
ruby 3.2.2
Rails 7.0.4.3

**Comment by DanL12186** [comment]
[Duplicate](https://github.com/alexrudall/ruby-openai/issues/421) of this PR

**Comment by alexrudall** [comment]
Closing for #421
