### ISSUE TITLE
Faraday::Error: :json is not registered on Faraday::Response

### ISSUE THREAD

**Issue by nathanmoreira1** [alexrudall/ruby-openai#451]
**Describe the bug**
When I try to make a request with client.chat(...), it returns this as an error.

When I start the server, I also get the following:
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/brdata-3.3.0/lib/brdata.rb:37: warning: already initialized constant FERIADOS_PATH
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/brdata-3.3.0/lib/brdata.rb:36: warning: previous definition of FERIADOS_PATH was here
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:15: warning: already initialized constant Faraday::FilePart
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.4.1/lib/faraday/file_part.rb:53: warning: previous definition of FilePart was here
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:16: warning: already initialized constant Faraday::ParamPart
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.4.1/lib/faraday/param_part.rb:5: warning: previous definition of ParamPart was here
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:17: warning: already initialized constant Faraday::Parts
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.4.1/lib/faraday/file_part.rb:61: warning: previous definition of Parts was here
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:18: warning: already initialized constant Faraday::CompositeReadIO
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.4.1/lib/faraday/file_part.rb:66: warning: previous definition of CompositeReadIO was here
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-multipart-1.0.4/lib/faraday/multipart.rb:21: warning: already initialized constant Faraday::UploadIO
/Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/faraday-1.4.1/lib/faraday/file_part.rb:59: warning: previous definition of UploadIO was here

**To Reproduce**
1. Install ruby-openia
2. Configure the openia.rb with your credentials
3. Try to make the request

**Desktop (please complete the following information):**
 - OS: macOS

**versions**
- rails: 5.2.3
- ruby-openia: latest

**Comment by nathanmoreira1** [comment]
Installing the "faraday_middleware" gem and putting this:

require "faraday_middleware"

in my openia.rb in the initializers folder, everything started to work fine

**Comment by nathanmoreira1** [comment]
Installing the "faraday_middleware" gem and putting this:

require "faraday_middleware"

in my openia.rb in the initializers folder, everything started to work fine

**Comment by ishields** [comment]
Just curious why this hasn't been made as a dependency of the gem if its required to work?
