### ISSUE TITLE
Documentation does not include tool choice option

### ISSUE THREAD

**Issue by Jbrito6492** [alexrudall/ruby-openai#452]
**Describe the bug**

The README example of using functions does not mention the tool choice parameter, which intermittently caused issues during implementation. Sometimes, the API would use our function, resulting in a `finish_reason` being `tool_calls`. Other times, the API would not use our function, with a `finish_reason` being `stop`.

**To Reproduce**
Follow the functions example in the README.

**Expected behavior**
We expected the function call to be used consistently with a `finish_reason` of `tool_calls`.

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexrudall** [comment]
Released in [v7](https://github.com/alexrudall/ruby-openai/releases/tag/v7.0.0)
