### ISSUE TITLE
Support for Assistants v2

### ISSUE THREAD

**Issue by josegm** [alexrudall/ruby-openai#455]
A new version of Assistants API is available.

Here's the migration path and changes needed: https://platform.openai.com/docs/assistants/migration

**Comment by bladerunnn** [comment]
Any update on supporting v2 @alexrudall?

**Comment by willywg** [comment]
TIP: You can use Assistants API v2 setting this monkey patch until someone make the correct solution:

```
module OpenAIPatch
  def beta(apis)
    dup.tap do |client|
      client.add_headers("OpenAI-Beta": apis.map { |k, v| "#{k}=v2" }.join(";"))
    end  
  end
end

OpenAI::Client.prepend(OpenAIPatch)
```

**Comment by alexrudall** [comment]
Released in [v7](https://github.com/alexrudall/ruby-openai/releases/tag/v7.0.0)
