### ISSUE TITLE
Support for Ruby 2.6

### ISSUE THREAD

**Issue by wasabigeek** [alexrudall/ruby-openai#47]
Hi, thanks for making this! I'd love if this was a little more flexible in terms of requirements e.g. Ruby version - is this something you are open to adding? We could use a matrix in the CI for test coverage.

**Comment by alexrudall** [comment]
Hi, no problem! Definitely, would welcome a PR on this, and it's on my todo list if not :)

**Comment by alexrudall** [comment]
Done, added compatibility for 2.5+ 

[https://rubygems.org/gems/ruby-openai/versions/1.3.1](https://rubygems.org/gems/ruby-openai/versions/1.3.1)
