### ISSUE TITLE
api_key instead of access_token? And client.audio is also changed?

### ISSUE THREAD

**Issue by jikkuatwork** [alexrudall/ruby-openai#506]
Did the API change?

Unlike in README, now it requires `api_key` instead of `access_token`?

Also, audio is not working?

```
require "openai"

client = OpenAI::Client.new(api_key: ENV["OPENAI_API_KEY"])

p client.audio
```

Gives:

```
❯ r spike.rb
spike.rb:5:in `<main>': undefined method `audio' for an instance of OpenAI::Client (NoMethodError)

p client.audio
        ^^^^^^
```

**Comment by alexrudall** [comment]
There's another gem called openai, could that be installed? If not, what version of ruby-openai are you using?

**Comment by jikkuatwork** [comment]
Yes! So sorry. I might have mistakenly installed it while trying to update the gem!

**Comment by alexrudall** [comment]
@jikkuatwork no problem, it happens a lot!

**Comment by jikkuatwork** [comment]
:)
