### ISSUE TITLE
Streaming for Assistant Run

### ISSUE THREAD

**Issue by stephenhighemprise** [alexrudall/ruby-openai#511]
It would be nice to use streaming when waiting for a message to come back from the Assistants API.  Is it on the roadmap to support the stream parameter for a run?

https://platform.openai.com/docs/api-reference/runs/createRun#runs-createrun-stream

**Comment by alexrudall** [comment]
You can already do this :) see [here](https://github.com/alexrudall/ruby-openai?tab=readme-ov-file#runs)

FYI most parameters are just passed through to OpenAI, so even new parameters should "just work"

**Comment by stephenhighemprise** [comment]
@alexrudall Thanks! I thought I had seen something like that but couldn't remember if it was over in RailsAI or what because I cycled through the page with find on all occurrences of stream but guess I blew past that.  :)
