### ISSUE TITLE
Configuration Object Pattern

### ISSUE THREAD

**Issue by aquaflamingo** [alexrudall/ruby-openai#84]
**Is your feature request related to a problem? Please describe.**
Hey there, cool library. I'm trying to integrate into a Rails application which typically follows the initializers convention and Configuration pattern. I'm wondering if you'd be open to a PR refactoring the library a bit to support this pattern. 

**Describe the solution you'd like**
Looking at the code as is, I think it would involve removing the dependency injection of the `access_token` into each of the sub classes like `Finetuning` and `Engines`, and instead pulling from a base library `Config` object, which is expected to contain the necessary credentials for access.

For example:
```
OpenAI::Configuration.configure do |c|
  c.access_token = "my_access_token"
end
```

Then the client could be instantiated without the access token. I started an implementation [here](https://github.com/alexrudall/ruby-openai/compare/main...aquaflamingo:aqf/add-conf?expand=1) but figured I'd get some input before I went too far forward.

**Comment by alexrudall** [comment]
Hey @aquaflamingo !

I think that would be really nice improvement, definitely open to your PR on that! Just need to handle both the existing ways of adding the token (`@access_token = access_token || ENV["OPENAI_ACCESS_TOKEN"]`) but it looks like you've already seen that. If you do a PR I'll review ASAP.
