### ISSUE TITLE
Could you add support for the moderations endpoint?

### ISSUE THREAD

**Issue by codev** [alexrudall/ruby-openai#93]
We will soon have to use this endpoint to classify output, unless I've misunderstood it isn't available at the moment:

https://beta.openai.com/docs/api-reference/moderations

Thanks, Marc

**Comment by alexrudall** [comment]
Hi Marc,

Thanks for the request! Just added and released this in [v1.5.0](https://rubygems.org/gems/ruby-openai/versions/1.5.0)
